# 输出格式
jmeter.save.saveservice.output_format=csv
jmeter.save.saveservice.print_field_names=true
jmeter.save.saveservice.data_type=false
jmeter.save.saveservice.label=true
jmeter.save.saveservice.response_code=true
jmeter.save.saveservice.response_data=false
jmeter.save.saveservice.response_message=false
jmeter.save.saveservice.successful=true
jmeter.save.saveservice.thread_counts=false
jmeter.save.saveservice.sample_count=false
jmeter.save.saveservice.assertion_results_failure_message=false

# 语言
language=zh_CN

# 分布式（可选）
# remote_hosts=192.168.1.101:1099,192.168.1.102:1099
# server.rmi.ssl.disable=true