-- ========== 用户 ==========
CREATE TABLE system_user (
                             id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             username     VARCHAR2(50)  NOT NULL UNIQUE,
                             password     VARCHAR2(100) NOT NULL,
                             nickname     VARCHAR2(50),
                             phone        VARCHAR2(20),
                             role         VARCHAR2(20)  DEFAULT 'USER' NOT NULL,
                             status       NUMBER(1)     DEFAULT 1,
                             create_time  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

-- ========== 影片 ==========
CREATE TABLE system_movie (
                              id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name         VARCHAR2(100) NOT NULL,
                              director     VARCHAR2(50),
                              actors       VARCHAR2(255),
                              type         VARCHAR2(50),
                              duration     NUMBER(10),
                              release_date DATE,
                              poster_url   VARCHAR2(255),
                              description  CLOB,
                              status       NUMBER(1) DEFAULT 1,
                              count        NUMBER(19) DEFAULT 0
);

-- ========== 影厅 ==========
CREATE TABLE system_hall (
                             id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             name         VARCHAR2(50) NOT NULL,
                             hall_type    VARCHAR2(20) NOT NULL,
                             row_count    NUMBER(10) NOT NULL,
                             col_count    NUMBER(10) NOT NULL
);

-- ========== 座位 ==========
CREATE TABLE system_seat (
                             id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             hall_id      NUMBER(19) NOT NULL,
                             seat_row     NUMBER(10) NOT NULL,
                             seat_col     NUMBER(10) NOT NULL,
                             seat_no      VARCHAR2(20) NOT NULL,
                             seat_type    VARCHAR2(20) DEFAULT 'NORMAL',
                             CONSTRAINT uk_hall_seat UNIQUE (hall_id, seat_row, seat_col)
);

-- ========== 排片 ==========
CREATE TABLE system_schedule (
                                 id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 movie_id     NUMBER(19) NOT NULL,
                                 hall_id      NUMBER(19) NOT NULL,
                                 start_time   TIMESTAMP NOT NULL,
                                 end_time     TIMESTAMP NOT NULL,
                                 price        NUMBER(10,2) NOT NULL,
                                 status       NUMBER(1) DEFAULT 1
);

-- ========== 订单 ==========
CREATE TABLE system_order (
                              id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              order_no      VARCHAR2(64) NOT NULL UNIQUE,
                              user_id       NUMBER(19) NOT NULL,
                              schedule_id   NUMBER(19) NOT NULL,
                              total_amount  NUMBER(10,2) NOT NULL,
                              order_type    VARCHAR2(20) DEFAULT 'NORMAL',
                              status        VARCHAR2(20) NOT NULL,
                              pay_time      TIMESTAMP,
                              expire_time   TIMESTAMP,
                              create_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_order_user ON system_order(user_id);
CREATE INDEX idx_order_status_expire ON system_order(status, expire_time);

-- ========== 票 ==========
CREATE TABLE system_ticket (
                               id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               order_id     NUMBER(19) NOT NULL,
                               schedule_id  NUMBER(19) NOT NULL,
                               seat_id      NUMBER(19) NOT NULL,
                               price        NUMBER(10,2) NOT NULL,
                               ticket_no    VARCHAR2(64) NOT NULL UNIQUE,
                               status       VARCHAR2(20) DEFAULT 'VALID',
                               CONSTRAINT uk_schedule_seat UNIQUE (schedule_id, seat_id)
);

-- ========== 秒杀活动 ==========
CREATE TABLE system_seckill_activity (
                                         id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         schedule_id   NUMBER(19) NOT NULL,
                                         seckill_price NUMBER(10,2) NOT NULL,
                                         stock         NUMBER(10) NOT NULL,
                                         start_time    TIMESTAMP NOT NULL,
                                         end_time      TIMESTAMP NOT NULL,
                                         status        NUMBER(1) DEFAULT 1
);

-- ========== 秒杀记录 ==========
CREATE TABLE system_seckill_record (
                                       id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       activity_id  NUMBER(19) NOT NULL,
                                       user_id      NUMBER(19) NOT NULL,
                                       order_no     VARCHAR2(64),
                                       create_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                       CONSTRAINT uk_act_user UNIQUE (activity_id, user_id)
);
