<script setup>
import { reactive, ref, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import request from '@/utils/request'
import { saveAuth } from '@/utils/auth'
const route=useRoute(),router=useRouter(),registering=computed(()=>route.path==='/register'),loading=ref(false),role=ref('USER')
const form=reactive({username:'',password:'',confirmPassword:'',phone:'',age:null,introduction:''})
const error=ref('')
async function submit(){error.value='';if(!form.username.trim()||!form.password){error.value='请填写用户名和密码';return}if(form.password.length<6){error.value='密码至少需要 6 位';return}if(registering.value){if(form.password!==form.confirmPassword){error.value='两次密码不一致';return}if(!/^1\d{10}$/.test(form.phone)){error.value='请输入有效的 11 位手机号';return}if(form.age!=null&&(form.age<1||form.age>120)){error.value='年龄应在 1 至 120 岁之间';return}}
loading.value=true;try{if(registering.value){await request.post('/auth/register',{username:form.username,password:form.password,phone:form.phone,age:form.age,introduction:form.introduction});ElMessage.success('注册成功，请登录');router.push('/login')}else{const data=await request.post('/auth/login',{username:form.username,password:form.password});const user=data.user||{id:data.userId,username:form.username,role:data.role||role.value};saveAuth({...data,user,token:data.token||data.accessToken});ElMessage.success('登录成功');router.push('/index')}}catch(e){error.value=e.message||'操作失败，请稍后重试'}finally{loading.value=false}}
</script>
<template><main class="auth-page"><div class="auth-card"><div class="auth-brand"><span>CINEMA · DISCOVER</span><h1>影视推荐平台</h1><p>{{ registering?'加入我们，开启下一场观影旅程':'欢迎回来，精彩电影等你发现' }}</p></div><div v-if="!registering" class="role-switch"><button :class="{active:role==='USER'}" @click="role='USER'">普通用户</button><button :class="{active:role==='ADMIN'}" @click="role='ADMIN'">管理员</button></div><form @submit.prevent="submit"><label>用户名<el-input v-model="form.username" placeholder="请输入用户名" autocomplete="username"/></label><label>密码<el-input v-model="form.password" type="password" show-password placeholder="请输入密码" autocomplete="current-password"/></label><template v-if="registering"><label>确认密码<el-input v-model="form.confirmPassword" type="password" show-password placeholder="请再次输入密码"/></label><label>手机号<el-input v-model="form.phone" placeholder="请输入手机号"/></label><label>年龄<el-input-number v-model="form.age" :min="1" :max="120" controls-position="right"/></label><label>个人简介<el-input v-model="form.introduction" type="textarea" :rows="2" placeholder="说说你喜欢什么电影"/></label></template><p v-if="error" class="error">{{ error }}</p><el-button native-type="submit" type="primary" :loading="loading" class="submit">{{ registering?'注册账户':'登录' }}</el-button></form><p class="switch">{{ registering?'已有账户？':'还没有账户？' }} <a @click="router.push(registering?'/login':'/register')">{{ registering?'立即登录':'立即注册' }}</a></p></div></main></template>
<style scoped>.auth-page{min-height:100vh;display:grid;place-items:center;background:linear-gradient(135deg,#667eea,#764ba2 58%,#87ceeb);padding:20px}.auth-card{width:min(100%,420px);background:white;border-radius:12px;padding:34px;box-shadow:0 22px 55px #2b1c6940}.auth-brand{text-align:center;margin-bottom:24px}.auth-brand span{font-size:11px;color:#667eea;font-weight:800;letter-spacing:1px}.auth-brand h1{margin:10px 0;font-size:26px;color:#333}.auth-brand p{font-size:13px;color:#999;margin:0}.role-switch{display:flex;background:#f0edfa;padding:4px;border-radius:7px;margin-bottom:18px}.role-switch button{flex:1;border:0;border-radius:5px;background:transparent;padding:9px;cursor:pointer;color:#666}.role-switch button.active{background:white;color:#5b4daa;box-shadow:0 2px 8px #3b2f8520}form{display:grid;gap:14px}form label{display:grid;gap:6px;font-size:13px;color:#555;font-weight:600}.error{color:#ff4444;font-size:13px;margin:0}.submit{width:100%;height:39px;background:#667eea;border-color:#667eea}.switch{text-align:center;color:#999;font-size:13px}.switch a{color:#667eea;cursor:pointer}.home-link{display:block;margin:auto;border:0;background:none;color:#777;cursor:pointer;font-size:12px}.home-link:hover,.switch a:hover{color:#764ba2}@media(max-width:500px){.auth-card{padding:25px}}
</style>



