<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { fetchMovie, posterFor } from '@/api/discovery'
import { isLoggedIn, getUser } from '@/utils/auth'
import PageBack from '@/components/PageBack.vue'
import ContentState from '@/components/ContentState.vue'
const route = useRoute(), router = useRouter(), movie = ref(null), loading = ref(true), error = ref(''), quantity = ref(1), rating = ref(0), busy = ref(false)
const total = computed(() => (Number(movie.value?.price || 40) * quantity.value).toFixed(2))
const scoreKey = computed(() => `cinema_rating_${getUser()?.id || 'guest'}_${movie.value?.id}`)
const distribution = computed(() => [1,2,3,4,5].map((star) => Number(movie.value?.[`scoreGrade${star}`] || (movie.value?.score ? Math.max(1, Math.round((movie.value.score / 5) ** (6-star) * 100)) : 0))))
const distributionMax = computed(() => Math.max(...distribution.value, 1))
onMounted(async()=>{try{movie.value=await fetchMovie(route.query.id)}catch{error.value='影片详情加载失败，请稍后重试'}finally{loading.value=false;rating.value=Number(localStorage.getItem(scoreKey.value)||0)}})
function rate(value){if(!isLoggedIn()){ElMessage.warning('请先登录后评分');router.push('/login');return}rating.value=value;localStorage.setItem(scoreKey.value,String(value));ElMessage.success('评分已保存，可随时修改')}
async function buy(){if(!isLoggedIn()){ElMessage.warning('请先登录后购票');router.push('/login');return}await ElMessageBox.alert('请进入具体场次完成数据库订单创建。','请选择场次');router.push('/screenings')}
</script>
<template><main class="detail-page"><div class="detail-wrap"><PageBack/><ContentState :loading="loading" :error="error"/><template v-if="movie"><div class="detail-content"><div class="cover"><img :src="posterFor(movie)" :alt="movie.name" @error="$event.target.style.visibility='hidden'"/></div><div class="movie-copy"><span class="kicker">FEATURE FILM</span><h1>{{ movie.name }}</h1><div class="tags"><span>{{ movie.type || '类型待更新' }}</span><span>{{ movie.startTime || '上映时间待定' }}</span><span>{{ (movie.count||0).toLocaleString() }} 次播放</span></div><p class="description">{{ movie.introduction || '这部影片暂时没有简介。' }}</p><div class="score-display"><b>★ {{ movie.score ? movie.score.toFixed(1) : '暂无评分' }}</b><span>观众评分</span></div><div class="rating-block"><strong>我的评分</strong><el-rate :model-value="rating" @change="rate" :colors="['#ffd93d','#ffd93d','#ffd93d']"/><small>{{ rating ? `已评 ${rating} 星，可修改` : '点亮星星，分享观影感受' }}</small></div><div class="distribution"><div v-for="(value,index) in distribution" :key="index"><span>{{ index+1 }} 星</span><div class="bar"><i :style="{width:`${value/distributionMax*100}%`}"/></div><span>{{ value }}</span></div></div></div></div><section class="buy-panel"><div><span class="kicker">购票信息</span><h2>准备好走进影院了吗？</h2><p>票价 <b>¥{{ movie.price || 40 }}</b> / 张 · 具体场次可进入选座购票</p></div><div class="buy-actions"><el-input-number v-model="quantity" :min="1" :max="10"/><strong>¥{{ total }}</strong><el-button type="primary" :loading="busy" @click="buy">立即购买</el-button><el-button @click="router.push('/screenings')">选择场次</el-button></div></section></template></div></main></template>
<style scoped>.detail-page{min-height:100vh;background:linear-gradient(135deg,#667eea,#764ba2 65%,#87ceeb);padding:25px 16px 65px}.detail-wrap{max-width:1100px;margin:auto}.detail-content{display:grid;grid-template-columns:minmax(230px,350px) 1fr;gap:50px;margin:35px 0;color:white}.cover{aspect-ratio:2/3;border-radius:9px;overflow:hidden;background:#9189b7;box-shadow:0 22px 40px #25174b44}.cover img{width:100%;height:100%;object-fit:cover}.kicker{font-size:12px;letter-spacing:1px;font-weight:800;opacity:.75}.movie-copy h1{font-size:40px;margin:12px 0 20px}.tags{display:flex;flex-wrap:wrap;gap:9px}.tags span{background:#ffffff29;border:1px solid #ffffff55;padding:7px 10px;border-radius:5px;font-size:13px}.description{font-size:15px;line-height:1.9;max-width:600px;margin:26px 0}.score-display{display:flex;align-items:baseline;gap:14px}.score-display b{font-size:36px;color:#ffd93d}.score-display span{opacity:.8}.rating-block{display:flex;align-items:center;gap:14px;margin:20px 0;flex-wrap:wrap}.rating-block small{opacity:.8}.distribution{max-width:420px}.distribution>div{display:flex;align-items:center;gap:10px;margin:5px 0;font-size:12px}.distribution span:first-child{width:35px}.bar{height:6px;flex:1;border-radius:10px;background:#ffffff40;overflow:hidden}.bar i{display:block;height:100%;background:#ffd93d}.buy-panel{display:flex;justify-content:space-between;align-items:center;gap:20px;background:white;border-radius:10px;padding:24px 30px}.buy-panel h2{font-size:20px;margin:8px 0}.buy-panel p{color:#666;margin:0}.buy-panel p b,.buy-actions strong{color:#ff6b6b}.buy-actions{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.buy-actions strong{font-size:23px}.buy-actions :deep(.el-button--primary){background:#667eea;border-color:#667eea}@media(max-width:700px){.detail-content{grid-template-columns:1fr;gap:24px}.cover{width:min(60vw,230px)}.movie-copy h1{font-size:30px}.buy-panel{align-items:start;flex-direction:column;padding:20px}}
</style>


