<script setup>
import { ref, nextTick } from 'vue'
import PageBack from '@/components/PageBack.vue'
const messages=ref([{role:'assistant',text:'你好！我是智能客服。关于电影、购票或订单，有什么想了解的？'}]),input=ref(''),loading=ref(false),list=ref(null)
function render(text){return text.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>')}
async function send(){const text=input.value.trim();if(!text||loading.value)return;messages.value.push({role:'user',text});input.value='';loading.value=true;await nextTick();list.value?.scrollTo(0,list.value.scrollHeight);setTimeout(async()=>{const reply=/订单|退款/.test(text)?'你可以在 **历史订单** 查看购票记录。退款请进入具体订单或联系客服处理。':/电影|推荐/.test(text)?'可以看看首页的热门推荐和电影排行榜，点开影片可查看简介与评分。':'我可以帮你了解电影推荐、购票与订单。你可以再具体描述一下问题。';messages.value.push({role:'assistant',text:reply});loading.value=false;await nextTick();list.value?.scrollTo(0,list.value.scrollHeight)},600)}
</script>
<template><main class="service-page"><div class="service-wrap"><PageBack/><div class="chat-card"><header><div class="ai-icon">✦</div><div><h1>智能客服</h1><span>随时为你解答</span></div><el-button text @click="messages=[{role:'assistant',text:'你好！我是智能客服。关于电影、购票或订单，有什么想了解的？'}]">清空对话</el-button></header><div ref="list" class="messages"><div v-for="(message,index) in messages" :key="index" class="message" :class="message.role"><div class="bubble" v-html="render(message.text)"/></div><div v-if="loading" class="message assistant"><div class="bubble">正在思考...</div></div></div><form @submit.prevent="send"><el-input v-model="input" placeholder="输入你的问题..." :disabled="loading"/><el-button type="primary" native-type="submit" :loading="loading">发送</el-button></form></div></div></main></template>
<style scoped>.service-page{min-height:100vh;background:linear-gradient(135deg,#667eea,#764ba2 65%,#87ceeb);padding:24px 16px}.service-wrap{max-width:880px;margin:auto}.chat-card{margin-top:20px;background:white;border-radius:10px;height:min(78vh,740px);min-height:500px;display:flex;flex-direction:column;overflow:hidden;box-shadow:0 18px 40px #28186135}header{display:flex;align-items:center;gap:12px;padding:17px 21px;border-bottom:1px solid #eee}header h1{font-size:18px;margin:0 0 3px}header span{font-size:12px;color:#999}header button{margin-left:auto}.ai-icon{display:grid;place-items:center;background:#ece7fa;color:#674aba;width:40px;height:40px;border-radius:7px;font-size:20px}.messages{flex:1;overflow:auto;padding:22px;background:#fbfaff}.message{display:flex;margin:12px 0}.message.user{justify-content:end}.bubble{max-width:min(75%,550px);background:white;padding:12px 15px;border-radius:8px;color:#444;line-height:1.6;box-shadow:0 2px 8px #1b123a0c}.user .bubble{background:#667eea;color:white}form{display:flex;gap:10px;padding:16px;border-top:1px solid #eee}form :deep(.el-button--primary){background:#667eea;border-color:#667eea}</style>
